CREATE TABLE IF NOT EXISTS parent_folders (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
    name TEXT UNIQUE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    parent_id INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, parent_id) ON CONFLICT REPLACE
);

CREATE TABLE IF NOT EXISTS words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    english TEXT NOT NULL,
    japanese TEXT NOT NULL,
    annotation TEXT,
    folder_id INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (english, japanese, folder_id) ON CONFLICT REPLACE
);

CREATE TABLE IF NOT EXISTS poss (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pos TEXT
);

create TABLE IF NOT EXISTS words_poss (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    words_id INTEGER poss_id INTEGER
);
